sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t thaeimos/docker-travis-aws-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true thaeimos/docker-travis-aws-demo npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-790577265452"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY